name: UltimateAddons
version: ${project.version}
main: dev.c0rex64.ultimateaddons.UltimateAddons
api-version: 1.20
author: c0re
description: Ultimate mechanics addons for your server
website: https://c0rex64.dev
depend: [ProtocolLib]

commands:
  ultimateaddons:
    description: Main plugin command
    aliases: [ua, uaddons]
    permission: ultimateaddons.admin
    
permissions:
  ultimateaddons.admin:
    description: Admin permission for UltimateAddons
    default: op
  ultimateaddons.weather:
    description: Weather mechanic permission
    default: true 